version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
      my-actions:
        patterns:
          - "xt0rted/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
          - "@types/eslint"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
      jest:
        patterns:
          - "@types/jest"
          - "jest"
          - "jest-*"
          - "ts-jest"
      semver:
        patterns:
          - "@types/semver"
          - "semver"
      typescript:
        patterns:
          - "ts-node"
          - "tslib"
          - "typescript"
