name: "dotnet sdk updater"

description: "Update global.json files with the latest SDK version"

author: "xt0rted"

branding:
  icon: "edit"
  color: "purple"

inputs:
  dry-run:
    description: "Checks if an update is available but doesn't update the file."
    required: false
    default: "false"

  file-location:
    description: "The location of the global.json to check."
    required: false
    default: "./"

outputs:
  channel:
    description: "The major and minor version of the sdk."

  cve-list:
    description: "A json array of any CVEs included in the release."

  dry-run:
    description: "Same value as the dry-run input."

  release-date:
    description: "The date of the release."

  release-notes:
    description: "A URL to the release notes for the release."

  release-version:
    description: "The version of the runtime for the release."

  security-release:
    description: "If this release contains security fixes."

  updated:
    description: "If the file was updated with a new version."

  updated-version-from:
    description: "The starting version in the global.json."

  updated-version-to:
    description: "The new version in the global.json."

  update-type:
    description: "The difference between the from and to version (major, premajor, minor, preminor, patch, prepatch, or prerelease)."

runs:
  using: "node16"
  main: "dist/index.js"
