name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22
          - 24

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run build

      - run: npm test

      - run: npm run package

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.8.3

  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22
          - 24

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run lint
